### ISSUE TITLE
Jak to zainstalować?

### ISSUE THREAD

**Issue by angryk** [qilin-editor/qilin-app#53]
Jak mogę pobrać i zainstalować ten program?

**Comment by Bartozzz** [comment]
Możesz [pobrać Qilina](https://github.com/qilin-editor/qilin-app/releases) odpowiadającą Twojemu systemowi operacyjnemu bądź spróbować zbudować go samemu. Więcej informacji w [poradniku](https://github.com/qilin-editor/qilin-app/blob/master/INSTALL.md). Daj znać czy sobie poradziłeś, to zamknę issue. 😁
